name: Create New C# Library

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version name for the new library'
        required: true
        default: '1.0.0'
      project:
        description: 'Select the project name'
        required: true
        type: choice
        options:
          - customtable
          - v2
          - commerceportal
          - payment

jobs:
  create-library:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Create new C# library
      run: |
        PROJECT_NAME="znode.${{ github.event.inputs.project }}.client.${{ github.event.inputs.version }}"
        mkdir $PROJECT_NAME
        cd $PROJECT_NAME
        dotnet new classlib --name $PROJECT_NAME --output .
        ls -la

    - name: Remove Class1.cs file
      run: |
        PROJECT_NAME="znode.${{ github.event.inputs.project }}.client.${{ github.event.inputs.version }}"
        rm $PROJECT_NAME/Class1.cs
        echo "Removed Class1.cs"

    - name: Add Newtonsoft.Json package
      run: |
        PROJECT_NAME="znode.${{ github.event.inputs.project }}.client.${{ github.event.inputs.version }}"
        cd $PROJECT_NAME
        dotnet add package Newtonsoft.Json

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Add new library: znode.${{ github.event.inputs.project }}.client.${{ github.event.inputs.version }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
